// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvjjb5YTYNFUfRCvqQRKOssHfgRuzzPrU',
    appId: '1:741551641935:web:184fee84fd04a4d454213a',
    messagingSenderId: '741551641935',
    projectId: 'frameworkmobile205411029',
    authDomain: 'frameworkmobile205411029.firebaseapp.com',
    storageBucket: 'frameworkmobile205411029.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABpJ3HTTOwWA68Rc-gR3SQONXBptuEFJ4',
    appId: '1:741551641935:android:f9980a77890de34654213a',
    messagingSenderId: '741551641935',
    projectId: 'frameworkmobile205411029',
    storageBucket: 'frameworkmobile205411029.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzjnuz7Ki0mv339P5PcE4GWmCw18KHULM',
    appId: '1:741551641935:ios:c60b0a5a32f228b854213a',
    messagingSenderId: '741551641935',
    projectId: 'frameworkmobile205411029',
    storageBucket: 'frameworkmobile205411029.appspot.com',
    iosClientId: '741551641935-lo6po4juae8rggee2f0o17q6uc28q16v.apps.googleusercontent.com',
    iosBundleId: 'com.example.coba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzjnuz7Ki0mv339P5PcE4GWmCw18KHULM',
    appId: '1:741551641935:ios:c60b0a5a32f228b854213a',
    messagingSenderId: '741551641935',
    projectId: 'frameworkmobile205411029',
    storageBucket: 'frameworkmobile205411029.appspot.com',
    iosClientId: '741551641935-lo6po4juae8rggee2f0o17q6uc28q16v.apps.googleusercontent.com',
    iosBundleId: 'com.example.coba',
  );
}
